version: '3.1'

services: 
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle_data:/opt/oracle/oradata
      
volumes:
  oracle_data:

# Oracle connection string
# jdbc:oracle:thin:@localhost:1521:XE

