version: '3.1'

services:

  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: aceacAppManagement
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
    driver: local