# redis docker without iredis
# version: "3"
# services:
#   redis:
#     image: redis
#     ports:
#       - 6379:6379

# # redis docker with iredis
# version: "3"
# services:
#   redis:
#     image: redis
#     ports:
#       - 6379:6379
#   iredis:
#     image: iredis/iredis
#     ports:
#       - 9001:9001
#     environment:
#       - REDIS_HOST=redis
#       - REDIS_PORT=6379

version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes","--save", "900 1", "--save", "300 10", "--save", "60 10000"]

  iredis:
    image: python:3.9-slim
    container_name: iredis-client
    depends_on:
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install iredis && iredis -h redis"
    stdin_open: true
    tty: true

volumes:
  redis_data:
    driver: local
